parameters:
    database_driver: pdo_pgsql
    database_host: 93.62.62.171
    database_port: '28542'
    database_name: 5cm_geo_copy
    database_user: 5cm_ext
    database_password: 10cm_int
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 53eb066526d505aa9a735ff60f837fba1109681c
    database_path: null
