Wolf\ScmCityBundle\Entity\comuniAttivati:
  type: entity
  fields:
    id:
        id: true
        type: integer
        generator:
            strategy: SEQUENCE
        sequenceGenerator:
            sequenceName: comuniattivati_id_seq
            allocationSize: 1
            initialValue: 1
    nome:
        type: string
        unique: true
        nullable: true
    pathFrontImage:
        type: string
        unique: true
        nullable: true
    pathFrontImageBlurred:
        type: string
        unique: true
        nullable: true
    dataIns:
        type: datetime
        nullable: true
    active:
        type: boolean
        nullable: true
  lifecycleCallbacks:
        prePersist: [setActiveValue, setDataInsValue]
