<?php

namespace Proxies\__CG__\Wolf\ScmCityBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class comuniAttivati extends \Wolf\ScmCityBundle\Entity\comuniAttivati implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setPathFrontImage($pathFrontImage)
    {
        $this->__load();
        return parent::setPathFrontImage($pathFrontImage);
    }

    public function getPathFrontImage()
    {
        $this->__load();
        return parent::getPathFrontImage();
    }

    public function setPathFrontImageBlurred($pathFrontImageBlurred)
    {
        $this->__load();
        return parent::setPathFrontImageBlurred($pathFrontImageBlurred);
    }

    public function getPathFrontImageBlurred()
    {
        $this->__load();
        return parent::getPathFrontImageBlurred();
    }

    public function setDataIns($dataIns)
    {
        $this->__load();
        return parent::setDataIns($dataIns);
    }

    public function getDataIns()
    {
        $this->__load();
        return parent::getDataIns();
    }

    public function setDataInsValue()
    {
        $this->__load();
        return parent::setDataInsValue();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nome', 'pathFrontImage', 'pathFrontImageBlurred', 'dataIns');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}