parameters:
#    wolf_scm_city.example.class: Wolf\ScmCityBundle\Example

services:
#    wolf_scm_city.example:
#        class: %wolf_scm_city.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
