wolf_scm_city_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: WolfScmCityBundle:Default:index }


WolfScmCityBundle_comuni:
    resource: "@WolfScmCityBundle/Resources/config/routing/comuniattivati.yml"
    prefix:   /comuni